# Generated by Django 5.2.8 on 2026-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('english', models.IntegerField()),
                ('computer', models.IntegerField()),
            ],
        ),
    ]
